config/routes.rb
Rails.application.routes.draw do
root 'nothingnesses#index'
resources :nothingnesses
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/nothingness.rb
class Nothingness < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/nothingnesses_controller.rb
class NothingnessesController < ApplicationController
  before_action :set_nothingness, only: [:show, :edit, :update, :destroy]

  # GET /nothingnesses
  # GET /nothingnesses.json
  def index
    @nothingnesses = Nothingness.all
  end

  # GET /nothingnesses/1
  # GET /nothingnesses/1.json
  def show
  end

  # GET /nothingnesses/new
  def new
    @nothingness = Nothingness.new
  end

  # GET /nothingnesses/1/edit
  def edit
  end

  # POST /nothingnesses
  # POST /nothingnesses.json
  def create
    @nothingness = Nothingness.new(nothingness_params)

    respond_to do |format|
      if @nothingness.save
        format.html { redirect_to @nothingness, notice: 'Nothingness was successfully created.' }
        format.json { render :show, status: :created, location: @nothingness }
      else
        format.html { render :new }
        format.json { render json: @nothingness.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nothingnesses/1
  # PATCH/PUT /nothingnesses/1.json
  def update
    respond_to do |format|
      if @nothingness.update(nothingness_params)
        format.html { redirect_to @nothingness, notice: 'Nothingness was successfully updated.' }
        format.json { render :show, status: :ok, location: @nothingness }
      else
        format.html { render :edit }
        format.json { render json: @nothingness.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nothingnesses/1
  # DELETE /nothingnesses/1.json
  def destroy
    @nothingness.destroy
    respond_to do |format|
      format.html { redirect_to nothingnesses_url, notice: 'Nothingness was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nothingness
      @nothingness = Nothingness.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def nothingness_params
      params.require(:nothingness).permit(:make, :model, :year)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nothingnesses_helper.rb
module NothingnessesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/nothingnesses/_form.html.erb
<%= form_with(model: nothingness, local: true) do |form| %>
  <% if nothingness.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(nothingness.errors.count, "error") %> prohibited this nothingness from being saved:</h2>

      <ul>
      <% nothingness.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :make %>
    <%= form.text_field :make, id: :nothingness_make %>
  </div>

  <div class="field">
    <%= form.label :model %>
    <%= form.text_field :model, id: :nothingness_model %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year, id: :nothingness_year %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/nothingnesses/edit.html.erb
<h1>Editing Nothingness</h1>

<%= render 'form', nothingness: @nothingness %>

<%= link_to 'Show', @nothingness %> |
<%= link_to 'Back', nothingnesses_path %>

app/views/nothingnesses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Nothingnesses</h1>

<table>
  <thead>
    <tr>
      <th>Make</th>
      <th>Model</th>
      <th>Year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @nothingnesses.each do |nothingness| %>
      <tr>
        <td><%= nothingness.make %></td>
        <td><%= nothingness.model %></td>
        <td><%= nothingness.year %></td>
        <td><%= link_to 'Show', nothingness %></td>
        <td><%= link_to 'Edit', edit_nothingness_path(nothingness) %></td>
        <td><%= link_to 'Destroy', nothingness, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Nothingness', new_nothingness_path %>

app/views/nothingnesses/new.html.erb
<h1>New Nothingness</h1>

<%= render 'form', nothingness: @nothingness %>

<%= link_to 'Back', nothingnesses_path %>

app/views/nothingnesses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Make:</strong>
  <%= @nothingness.make %>
</p>

<p>
  <strong>Model:</strong>
  <%= @nothingness.model %>
</p>

<p>
  <strong>Year:</strong>
  <%= @nothingness.year %>
</p>

<%= link_to 'Edit', edit_nothingness_path(@nothingness) %> |
<%= link_to 'Back', nothingnesses_path %>